main: skyblock.SkyblockMain
name: SkyblockPlugin
version: 0.1
api-version: 1.16
commands:
  skyblock:
    description: Teleports you to your skyblock. If you don't already have one, one will be created for you.
    usage: /<command>
  warp:
    description: Warps you into a specific world
    usage: /<command>
  create_world:
    description: Creates a new void world you can warp to
    usage: /<command>