main: skyblock.SkyblockMain
name: SkyblockPlugin
version: 0.1
api-version: 1.16
depend: [ProtocolLib]
commands:
  warp:
    description: Warps you into a specific world
    usage: /<command>
  create_world:
    description: Creates a new void world you can warp to
    usage: /<command>
  fp_test:
    description: Fake player test
    usage: /<command>
  structurizer:
    description: Creates a structure file with the specified blocks
    usage: /<command>