main: skyblock.SkyblockMain
name: SkyblockPlugin
version: 0.1
api-version: 1.16
commands:
  skyblock:
    description: Teleports you to your skyblock. If you don't already have one, one will be created for you.
    usage: /<command>